### ISSUE TITLE
Issue when upgrading next to 13.5.6

### ISSUE THREAD

**Issue by jbtheard** [sofn-xyz/mailing#493]
**Describe the bug**
UI error:
```
Cannot find module 'next/dist/shared/lib/html-context.js'
```

**To Reproduce**
Upgrade next dependency to 13.5.6

**Expected behavior**
Should work as with 13.4.16 (last version I know to be working)
